services:
  - name: frontend
    type: web
    buildCommand: npm install && npm run build
    
  - name: backend
    type: web
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend:app
